### ISSUE TITLE
Arduino support?

### ISSUE THREAD

**Issue by edorgeville** [balena-os/balena-iot2000#19]
Hi,
A major feature of the IOT2020/2040 is to run Arduino programs alongside Linux.
Deploying such programs is done by flashing the [example image](https://support.industry.siemens.com/cs/attachments/109741799/Example_Image_V2.2.0.zip) onto the microSD card and booting, then using the MicroUSB port on the device, selecting the right COM port in the Arduino IDE and using the "Upload" button.
Unfortunately, when using the BalenaOS/ResinOS image (either from the cloud panel or the [homepage](https://files.resin.io/resinos/iot2000/2.12.7%2Brev2.dev/image/resin.img.zip)), the IOT2020 won't show up in both the Arduino IDE and Windows Device Manager.
Is Arduino supported? If not, is it a planned feature? We are trying out BalenaOS as a replacement to the base image but Arduino support is a must have. 
Cheers!

**Comment by ZubairLK** [comment]
Some discussion on this in the forums: https://forums.balena.io/t/iot2000-arduino-support/4373

**Comment by floion** [comment]
Discussion carried out in forums, closing here
